name: unit-tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  unit-tests:
    name: unit-tests
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-unit-tests
      cancel-in-progress: true
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run the tests
        run: bun test
        env:
          TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          CI: true 
